name: Make Zip

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - run: cp ./build/index.js .
      - run: tar -czf release.zip index.js package.json
      - run: mkdir downloads
      - run: mv release.zip ./downloads
      - name: artifact
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: downloads
